title: Xen's personal web-page
author: Xen
email: xen-dev@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  My maintained projects, documentation, scripts, tips, and sometimes 
  my thoughts... all here.
url: https://xen-e.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  xen-e

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
excerpt_separator: <!--more-->

# "/page:num/" is important because is used to check if user is in front page, keep it
paginate: 5
paginate_path: "/page:num/"

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html, index.html]
    
# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/
    